### ISSUE TITLE
can't run on normal mode 

### ISSUE THREAD

**Issue by vickydasta** [daffl/mysam#15] opened 2016-01-06 17:44 UTC
it got crash (so far, i don't have any experience with electron, but it's seems to be electron is the problem here) as i tried to run mysam on server mode, it runs, but only showing the loading screen. 

`$ sudo mysam` 

bellow are the error logs: 

```
sudo mysam 
Error: Command failed: /bin/sh -c npm ls --depth 0 --parseable -g
npm ERR! max depth reached: coffee-script@1.10.0, required by undefined@undefined
npm ERR! max depth reached: express-generator@4.13.1, required by undefined@undefined
npm ERR! max depth reached: forever@0.15.1, required by undefined@undefined
npm ERR! max depth reached: mysam@0.1.2, required by undefined@undefined
npm ERR! max depth reached: nodebootstrap@3.2.2, required by undefined@undefined
npm ERR! max depth reached: socket.io@1.3.7, required by undefined@undefined
npm ERR! max depth reached: supervisor@0.9.1, required by undefined@undefined
npm ERR! not ok code 0

    at ChildProcess.exithandler (child_process.js:215:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
Failed to get crash dump id.
Report Id: 
```

**Comment by daffl** [comment] 2016-01-06 19:09
That does look like Electron. I don't think you have to run with sudo but that probably doesn't make a difference in this case. I assume this is on Linux?

**Comment by vickydasta** [comment] 2016-01-07 03:58
yes, i run it on Linux Mint, 
```
Uncaught Exception:
Error: EACCES: permission denied, open '/usr/local/lib/node_modules/mysam/db-data/configuration'
    at Error (native)
```

when it runs without sudo.

**Comment by daffl** [comment] 2016-01-07 15:10
This may be related to https://github.com/atom/atom/issues/4892 and I was able to reproduce the segfault in Ubuntu as well. I just released a new MySam version (0.1.4) with a newer version of Electron which fixed the issue for me. Please try installing that version and let me know if it works.

**Comment by daffl** [comment] 2016-01-09 19:21
Closing since I could reproduce the issue and the fix. Please reopen if the problem still persists for you.

**Closed by daffl** 2016-01-09 19:21 UTC

**Comment by vickydasta** [comment] 2016-01-10 05:16
OK :+1:
